### ISSUE TITLE
API not verifying 

### ISSUE THREAD

**Issue by amstrackbein** [vlasscontreras/gragrid#9]
No matter what I do - the API key will not verify. Any solutions?

**Comment by havenindustries** [comment]
We are having the same problem. It's not clear to me what could be causing this. Any ideas?

**Comment by havenindustries** [comment]
What version of PHP does this plugin expect on the server? I can choose between 7.3, 7.4, and 8.0

**Comment by havenindustries** [comment]
For what it is worth 1.0 has the same issue as 1.1 with the api_key not validating when it is definitely valid.

**Comment by vlasscontreras** [comment]
Should work with PHP 7.2+. I'll be checking what's going on with this issue this weekend.

Thank you for reporting! 🙏🏻

**Comment by vlasscontreras** [comment]
Looks like the issue is due to the fact that this plugin uses the Legacy Marketing Campaigns API. I'll update it to use the new Marketing Campaigns API.

Thanks again, @amstrackbein and @havenindustries 🙏🏻

**Comment by havenindustries** [comment]
Excellent work! It is working perfectly for me right now. Thank you so much for updating it!

**Comment by amstrackbein** [comment]
Thank you - works great!!
